### PR TITLE
Fix match errors for elixir v1.3.0

### PR DESCRIPTION
**Pull request by codyjroberts**

### CODE REVIEW

**Comment by bcardarella** [comment]
I'd prefer to use this style instead https://github.com/DockYard/json_api_assert/blob/master/test/assert_data_test.exs#L23-L30

**Comment by codyjroberts** [comment]
Upon copying that style and doing some TDD I ran into a case where my test passed without even writing anything yet.  I can't recall what test it was now, but I remember replacing it with `assert_raise/3` caused it to fail.  It may have very well been a mistake on my part. However, it might have to do with the else clause in `assert_raise/2`?

https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/assertions.ex#L524

**Comment by codyjroberts** [comment]
At first I wasn't sure why you preferred this style but it makes complete sense after seeing this test:

https://github.com/DockYard/json_api_assert/blob/master/test/refute_relationship_test.exs#L78

I double checked all the existing tests by adding an else clause and everything looks good.  Would you be opposed to adding else clauses, similar to my latest commit, for good measure?

**Comment by bcardarella** [comment]
I'm not a fan of regex for assertion messages as it could allow something to slip through the cracks. Elixir 1.3 introduced some changes to how they render the messages from `ExUnit.Assertions` https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/assertions.ex#L37

this means we'd have to inject `\n\n` for every message. Or we can do what Elixir does internally to check which is what we have here.

**Comment by codyjroberts** [comment]
That makes sense.  I'm just concerned about the cases where the exception is not raised as desired.  Without an else clause in the try/rescue the test will pass although it's not working as intended.

**Comment by bcardarella** [comment]
Can you rive me an example?

**Comment by bcardarella** [comment]
Nm, this makes sense. Merging.

**Pull request merged**
