### PR TITLE
Enforce top-level member specs

### PR DESCRIPTION
**Pull request by codyjroberts**
Work in progress.  The assert_jsonapi function seemed to be the best place for these checks.  Thoughts?  

Addresses #7

### CODE REVIEW

**Comment by bcardarella** [comment]
I agree with the intent, but maybe the implementation is in the wrong function. Let me explain my thoughts:

I'd like to provide a function called `json_api_response` that can be used instead of https://hexdocs.pm/phoenix/Phoenix.ConnTest.html#json_response/2

Ideally we'd do something like:

``` elixir
conn
|> json_api_response(200)
|> assert_data(...
```

`json_api_response/2` would audit the payload to ensure it is a properly formed JSON API payload. The assertion this PR runs would be one of the assertions during that audit.

Now, back to the original question. Does this assertion belong in `assert_jsonapi`? It could, as long as we don't make this function a general dumping ground. Thoughts?

**Comment by codyjroberts** [comment]
For some reason my edit didn't go through.  The spec says that the top-level jsonapi object is optional, so I think it would be better if we grouped these requirements into a separate function.  Or we can make the object an optional parameter on `json_api_response`?

I have some free time tomorrow.  I'll read into `json_response/2` and see if I can put something more concrete together.

**Comment by bcardarella** [comment]
I suspect that `json_api_response(conn, status)` can be implemented as:

``` elixir
def json_api_response(conn, status) do
  Phoenix.ConnTest.json_response(conn, status)
  |> assert_jsonapi()
end
```

**Comment by codyjroberts** [comment]
Should we use `Phoenix.ConnTest.json_response/2`? Internally that function uses `response_content_type(conn, :json)` to ensure the content type is json.  We should be ensuring that the content-type is `application/vnd.api+json`.  Also, is it wise to have Phoenix as a dependency?

https://github.com/phoenixframework/phoenix/blob/00bd406d38403822a1eee8cc2d08d8cf6f1ab51c/lib/phoenix/test/conn_test.ex#L299

**Comment by bcardarella** [comment]
Both good points. Seems easy enough to reimplement

https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/test/conn_test.ex#L407-L416

**Comment by codyjroberts** [comment]
Hmm.  `json_response/2` seems to handle the `"application/vnd.api+json"` content-type as is.  Though we should be explicit and raise for all other MIME types.

https://github.com/phoenixframework/phoenix/blob/master/test/phoenix/test/conn_test.exs#L218-L251

I'm having success with reimplementing `json_response/2`, but I'm concerned with the duplication.  We'll have to use Poison and Plug as dependencies.  I feel it might be cleaner to add another function or add to `assert_jsonapi/2`.  

Or we could try to convince the Phoenix team to implement `json_api_response/2`; if only for the MIME-type enforcement, leaving the rest to this library.

I'll continue with the original intention as you said

> The assertion this PR runs would be one of the assertions during that audit.

The separation of concerns might become more apparent as I work on  it.

**Pull request merged**
